//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub google_id: String,
    pub username: String,
    pub username_normalized: Option<String>,
    pub email: String,
    pub avatar_url: Option<String>,
    pub username_updated_at: Option<DateTimeWithTimeZone>,
    pub age_confirmed_at: Option<DateTimeWithTimeZone>,
    pub terms_accepted_at: Option<DateTimeWithTimeZone>,
    pub terms_accepted_version: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::likes::Entity")]
    Likes,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    #[sea_orm(has_many = "super::videos::Entity")]
    Videos,
}

impl Related<super::likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Likes.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::videos::Entity> for Entity {
    fn to() -> RelationDef {
        super::likes::Relation::Videos.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::likes::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
